### ISSUE TITLE
Possibly useless files?

### ISSUE THREAD

**Issue by jasonli0616** [Flizzyclone/kevin#11]
What exactly does [start.bat](https://github.com/Flizzyclone/kevin/blob/master/start.bat) and [starboard.bat](https://github.com/Flizzyclone/kevin/blob/master/starboard.bat) do if you can just `npm start` and `npm run starboard`?

Those two files literally runs the exact same thing that `npm start` and `npm run starboard` runs

**Comment by KZiad** [comment]
it's probably for convenience.

**Comment by Flizzyclone** [comment]
its just useful for me when im working on kevin to have the two batch files there instead of going into command prompt again and again, they can probably be .gitignore'd but really it probably doesn't matter
